// Crashlytics bootstrap — NOT wired up yet.
//
// This file is intentionally never imported/called from main.dart (or
// anywhere else) yet. There is no Firebase project for YuruNavi at this
// time, so calling `Firebase.initializeApp()` with no valid config would
// crash the app immediately on launch.
//
// `initCrashReporting` takes the `FirebaseOptions` as a parameter rather
// than importing the generated `lib/firebase_options.dart` directly, since
// that file does not exist yet — it is normally generated by running
// `flutterfire configure`, which requires a Firebase account login. Once it
// exists, the caller in `main.dart` should pass
// `DefaultFirebaseOptions.currentPlatform` from that generated file.
//
// See loop/RELEASE_ROADMAP.md item 5 for the remaining manual setup steps.
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';

/// Initializes Firebase + Crashlytics and wires up global error handlers.
///
/// Call this as the first two lines of `main()`, after
/// `WidgetsFlutterBinding.ensureInitialized()`, once
/// `android/app/google-services.json` and `lib/firebase_options.dart` exist,
/// passing `DefaultFirebaseOptions.currentPlatform` as [options].
/// Not called anywhere yet — see the TODO in `lib/main.dart`.
Future<void> initCrashReporting(FirebaseOptions options) async {
  await Firebase.initializeApp(options: options);

  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };
}
